### ISSUE TITLE
broken links "PyZen" and "Fork me on github"

### ISSUE THREAD

**Issue by florentx** [coderanger/flask-zen#1]
The links are broken in the doc page: http://packages.python.org/Flask-Zen/

PyZen should target http://pypi.python.org/pypi/PyZen
github should target http://github.com/coderanger/flask-zen

**Comment by coderanger** [comment]
Fixed in http://github.com/coderanger/flask-zen/commit/7de740c83634383375203410c685fcafcc04f837 . Thanks!
