### ISSUE TITLE
New pypi version?

### ISSUE THREAD

**Issue by deadbeef404** [coderanger/flask-zen#4]
Hi @coderanger!

Is there any chance of getting the latest version of this code onto PyPI any time soon?

Having to change flaskext to flask.ext manually is a bit of a pain.

Thanks for your time! :)

**Comment by coderanger** [comment]
Do people still use this? I was under the impression flask-script was mostly dead, and py.test has a better test runner anyway.

**Comment by deadbeef404** [comment]
Abandoned using this due to changes in the project. Closing.
